working_dir: /home/rajiv/programming/kmds_migration/olist_migration
structural_type: wide and short
country_code: br
featurization_input_data: data/dd_cleaner/olist_daily_orders_prepared_clean.csv
metadata_file: data_dictionary/olist_example_dd.csv
featurization_output_dir: data
sp_freq_prod_file: SP_2017_freq_prod_weekly_sales_prepared.csv
sp_freq_prod_parquet: SP_2017_freq_prod_weekly_sales_prepared.parquet
pipeline:
  - name: "Load Featurization Input Dataset"
    method: "load_raw_data"
  - name: "Drop incomplete order rows"
    method: "validate_required_columns"
  - name: "Build SP 2017 Weekly Product Matrix"
    method: "build_sp_weekly_product_matrix"
